In [1]:
!pwd

/Users/rahulsingh/Desktop/python_book


In [2]:
!ls

Jupyter.ipynb Notes.txt     NumPy.ipynb   hello.py      myscript.py


images—particularly digital images can be thought of as simply two- dimensional arrays of numbers representing pixel brightness across the area.

Sound clips can be thought of as one-dimensional arrays of intensity versus time.

Text can be converted in various ways into numerical representations, such as binary digits representing the frequency of certain words or pairs of words. 

NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers.

NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

In [5]:
import numpy as np

In [6]:
np.__version__

'1.26.4'

In [7]:
In[6]

'np.__version__'

In [8]:
Out[6]

'1.26.4'

# Understanding Data Types in Python

In [9]:
L = list(range(10))

In [10]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
type(L[0])

int

In [12]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(L2[0])

str

In [14]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [15]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Here, 'i' is a type code indicating the contents are integers.

In [16]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

Remember that unlike Python lists, NumPy arrays can only contain data of the same type. 

If the types do not match, NumPy will upcast them according to its type promo‐ tion rules; here, integers are upcast to floating point:

In [17]:
np.array([3.14,4,5,6])

array([3.14, 4.  , 5.  , 6.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [18]:
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lists, which are always one-dimensional sequences, NumPy arrays can be multidimensional.

In [24]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [25]:
# Create a length-10 integer array filled with 0s
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Create a 3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
# Create a 3x3 array of uniformly distributed \
# pseudorandom values between 0 and 1
np.random.random((3,3))

array([[0.98581261, 0.10458764, 0.78748059],
       [0.37019616, 0.14428973, 0.47215449],
       [0.43975316, 0.51274027, 0.52396253]])

In [35]:
# Create a 3x3 array of uniformly distributed 
# pseudorandom values between 0 and 1
np.random.normal(0,1,(3,3))

array([[-1.43137961, -0.31984503,  0.1385818 ],
       [ 1.19654725, -0.29374762,  2.85815754],
       [-0.85123982, -0.33820729, -0.4910674 ]])

In [36]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[1, 9, 2],
       [0, 3, 4],
       [6, 2, 9]])

In [37]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# Create an uninitialized array of three integers; the values will be 
# whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

NumPy Standard Data Types

In [39]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [40]:
 np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)