# Introducing Pandas Objects

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.Series([0.25,0.5,0.75,1.0])

The Series combines a sequence of values with an explicit sequence of indices, which we can access with the values and index attributes.

In [10]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [11]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [12]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
data[1]

0.5

In [14]:
data[0:3]

0    0.25
1    0.50
2    0.75
dtype: float64

the Pandas Series is much more general and flexible than the
one-dimensional NumPy array that it emulates.

In [16]:
data = pd.Series([1.1,4.1,3.1,12.2],index=['a','b','c','d'])

In [17]:
data

a     1.1
b     4.1
c     3.1
d    12.2
dtype: float64

In [18]:
data['a']

1.1

In [22]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                  index=[2, 5, 3, 7])

In [23]:
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

Series as Specialized Dictionary

In [26]:
population_dic = { 'cali':123213,'texas':12312,
                  'florida':12356634,'ny':987654657,
                  'penn':874213
                    }
population = pd.Series(population_dic)
population

cali          123213
texas          12312
florida     12356634
ny         987654657
penn          874213
dtype: int64

In [27]:
population['cali']

123213

In [28]:
# supports array-style operations such as slicing:
population['cali':'ny']

cali          123213
texas          12312
florida     12356634
ny         987654657
dtype: int64

Constructing Series Objects

pd.Series(data, index=index)

In [29]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [30]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [31]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [32]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[1, 2])
# index can be explicitly set to control the order or the subset of keys used

1    b
2    a
dtype: object

The Pandas DataFrame Object

In [36]:
area_dict = {'cali': 423967, 'texas': 695662, 'florida': 170312,
                      'ny': 141297, 'penn': 119280}
area = pd.Series(area_dict)
area

cali       423967
texas      695662
florida    170312
ny         141297
penn       119280
dtype: int64

In [37]:
states = pd.DataFrame({'population':population,
                      'area':area})
states

population    area
cali         123213  423967
texas         12312  695662
florida    12356634  170312
ny        987654657  141297
penn         874213  119280

In [38]:
states.index

Index(['cali', 'texas', 'florida', 'ny', 'penn'], dtype='object')

In [39]:
states.columns

Index(['population', 'area'], dtype='object')

In [40]:
states['area']

cali       423967
texas      695662
florida    170312
ny         141297
penn       119280
Name: area, dtype: int64

A DataFrame is a collection of Series objects, and a single-column DataFrame can be constructed from a single Series:

In [41]:
pd.DataFrame(population,columns=['population'])
population

cali          123213
texas          12312
florida     12356634
ny         987654657
penn          874213
dtype: int64

In [42]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [43]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

if some keys in the dictionary are missing, Pandas will fill them in with NaN values 

In [45]:
# From a two-dimensional NumPy array
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],index = ['a','b','c'])

foo       bar
a  0.803719  0.522486
b  0.624410  0.367773
c  0.365304  0.811926

In [49]:
pd.DataFrame(
             columns=['foo', 'bar'],index = ['a','b','c'])

foo  bar
a  NaN  NaN
b  NaN  NaN
c  NaN  NaN

In [51]:
pd.DataFrame(5,
             columns=['foo', 'bar'],index = ['a','b','c'])

foo  bar
a    5    5
b    5    5
c    5    5

In [59]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [61]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

The Pandas Index Object

In [62]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [63]:
ind[1]

3

In [64]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [65]:
print(ind.size,ind.shape,ind.ndim,ind.dtype)

5 (5,) 1 int64


In [66]:
# One difference between Index objects and NumPy arrays is that the indices are
# immutable—that is, they cannot be modified via the normal means:
ind[1] = 0

TypeError: Index does not support mutable operations

Index as Ordered Set

In [67]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [68]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [69]:
indA.union(indB)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [71]:
indA.symmetric_difference(indB)

Index([1, 2, 9, 11], dtype='int64')

# Data Indexing and Selection

In [72]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])

In [73]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [74]:
data['a']

0.25

In [75]:
'a' in data

True

In [76]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [81]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [82]:
data['e'] = 1.25

In [83]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [84]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

Notice that when slicing with an explicit index (e.g., data['a':'c']), the final index is included in the slice, 

while when slicing with an implicit index (e.g., data[0:2]), the final index is excluded from the slice.

In [85]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [86]:
# masking
data[(data>0.3)&(data<0.8)]

b    0.50
c    0.75
dtype: float64

In [87]:
# fancy indexing 
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

Indexers: loc and iloc

In [88]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [89]:
# explicit index when indexing
data[1]

'a'

In [90]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes,

First, the loc attribute allows indexing and slicing that always references the explicit index:

In [92]:
data.loc[1]

'a'

In [94]:
data.loc[1:3]

1    a
3    b
dtype: object

The iloc attribute allows indexing and slicing that always references the implicit Python-style index:

In [95]:
data.iloc[1]

'b'

In [96]:
data.iloc[1:3]

3    b
5    c
dtype: object

Data Selection in DataFrames

In [98]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                           'Florida': 170312, 'New York': 141297,
                           'Pennsylvania': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505,
                          'Florida': 21538187, 'New York': 20201249,
                          'Pennsylvania': 13002700})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [101]:
data['area'] # dictionary-style indexing of the column name

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [102]:
data.area # attribute-style access with column names 

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

DataFrame as Two-Dimensional Array

In [103]:
data.values

array([[  423967, 39538223],
       [  695662, 29145505],
       [  170312, 21538187],
       [  141297, 20201249],
       [  119280, 13002700]])

In [105]:
data.T # transpose

California     Texas   Florida  New York  Pennsylvania
area      423967    695662    170312    141297        119280
pop     39538223  29145505  21538187  20201249      13002700

In [106]:
data.values[0]

array([  423967, 39538223])

In [109]:
data.loc[data.area > 120, ['pop', 'area']]

pop    area
California    39538223  423967
Texas         29145505  695662
Florida       21538187  170312
New York      20201249  141297
Pennsylvania  13002700  119280

# Operating on Data in Pandas

In [110]:
import pandas as pd
import numpy as np

In [112]:
rng = np.random.default_rng(42)
ser = pd.Series(rng.integers(0,10,4))
ser

0    0
1    7
2    6
3    4
dtype: int64

In [114]:
df = pd.DataFrame(rng.integers(0,10,(3,4)),columns=['A','B','C','D'])

In [115]:
df

A  B  C  D
0  4  8  0  6
1  2  0  5  9
2  7  7  7  7

In [116]:
np.exp(ser)

0       1.000000
1    1096.633158
2     403.428793
3      54.598150
dtype: float64

In [117]:
np.sin(df*np.pi/4)

A             B         C         D
0  1.224647e-16 -2.449294e-16  0.000000 -1.000000
1  1.000000e+00  0.000000e+00 -0.707107  0.707107
2 -7.071068e-01 -7.071068e-01 -0.707107 -0.707107

In [118]:
# Index Alignment in Series
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                          'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29145505,
                                'Florida': 21538187}, name='population')

In [119]:
population/area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

In [120]:
area.index.union(population.index)

Index(['Alaska', 'California', 'Florida', 'Texas'], dtype='object')

In [121]:
A = pd.Series([2, 4, 6], index=[0, 1, 2]) 
B = pd.Series([1, 3, 5], index=[1, 2, 3]) 
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [123]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

# Handling Missing Data

In [124]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [126]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [128]:
x[0] = None 
x
# Notice that in addition to casting the integer array to floating point, Pandas automati‐ cally converts the None to a NaN value.

0    NaN
1    1.0
dtype: float64

In [129]:
# Detecting Null Values
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [130]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [131]:
data[data.notnull()] #Boolean masks

0        1
2    hello
dtype: object

In [132]:
# Dropping Null Values
data.dropna()

0        1
2    hello
dtype: object

In [133]:
df = pd.DataFrame([[1,      np.nan, 2],
                 [2,      3,      5], [np.nan, 4,      6]])

In [134]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [137]:
df.dropna() # We cannot drop single values from a DataFrame; we can only drop entire rows or col‐ umns. 

0    1  2
1  2.0  3.0  5

In [138]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [139]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [140]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

You can also specify how='all', which will only drop rows/columns that contain all null values:

In [143]:
df.dropna(axis='rows', thresh=3)
# Here, the first and last rows have been dropped because they each contain only two
# non-null values.

0    1  2   3
1  2.0  3.0  5 NaN

Filling Null Values

In [145]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'),
                 dtype='Int32') 

In [146]:
data

a       1
b    <NA>
c       2
d    <NA>
e       3
dtype: Int32

In [147]:
data.fillna(0)

a    1
b    0
c    2
d    0
e    3
dtype: Int32

In [153]:
# forward fill 
data.fillna(method='ffill')

/var/folders/bt/35f6qmss40lcsmbmj3srx0zc0000gn/T/ipykernel_2226/3173140211.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


a    1
b    1
c    2
d    2
e    3
dtype: Int32

In [164]:
# back fill 
data.fillna(method='bfill')

/var/folders/bt/35f6qmss40lcsmbmj3srx0zc0000gn/T/ipykernel_2226/1686884525.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')


a    1
b    2
c    2
d    3
e    3
dtype: Int32

In [165]:
df.fillna(method='ffill', axis=1)

/var/folders/bt/35f6qmss40lcsmbmj3srx0zc0000gn/T/ipykernel_2226/901808322.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1)


0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

if a previous value is not available during a forward fill, the NA value remains.